require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config.ru'
    - 'config/environments/**/*'
    - 'Gemfile'

Style/Documentation:
  Enabled: false

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/NamedSubject:
  Enabled: false
