name: Bundle Audit

on:
  push:
    branches:
    - main
jobs:
  bundle-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
      - name: bundle-audit install
        run: |
          gem install bundle-audit
          bundle-audit update
      - name: Patch-level verification for Bundler
        run: |
          bundle-audit
